### ISSUE TITLE
edit CONVENTION.md

### ISSUE THREAD

**Issue by intersignature** [it-kmitl-2018/group4#6]

**Comment by champillon** [comment]
สำหรับที่ไม่ใช่ convention ถ้าจะทำให้ได้คะแนนต้องเปิด Issue และเปิด PR นะครับ ถ้า push ลง master ตรง พี่ตรวจให้คะคแนนไม่ได้ เพราะไม่รู้ว่า code ส่วนไหนแยกกันออกมาบ้างนะครับ

**Comment by intersignature** [comment]
ok ครับ
